spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
  datasource:
    plataform: postgres
    url: jdbc:postgresql://localhost:5432/hyper
    username: hyperUser
    password: hyperPass
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
    ignore-missing-migrations: false
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 120MB
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: undefined@gmail.com
#    password: undefined
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

api:
  security:
    token:
      secret: ${JWT_SECRET:lala}

server:
  port: 443
  ssl:
    enabled: true
    key-store: /home/Hyper:SSL.p12
    key-store-password: hyperPass
    key-store-type: PKCS12
    key-alias: hyperAlias
