CREATE TABLE ARTIST (
	ID BIGINT NOT NULL,
    CREDITS DECIMAL NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE ARTIST_SEQ START WITH 1;

ALTER TABLE ARTIST ADD PRIMARY KEY (ID);
