CREATE TABLE LEADS (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TEXT VARCHAR(200) NOT NULL
);

ALTER TABLE LEADS ADD CONSTRAINT LEADS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);