CREATE TABLE ALBUM (
	ID BIGINT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    RELEASE_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    ARTIST BIGINT,
    RECORD BIGINT,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE ALBUM_SEQ START WITH 1;

ALTER TABLE ALBUM ADD PRIMARY KEY (ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_RECORD_ID_FK FOREIGN KEY (RECORD) REFERENCES RECORD(ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_ARTIST_ID_FK FOREIGN KEY (ARTIST) REFERENCES ARTIST(ID);