CREATE TABLE COLLECTION_TRACKS (
    COLLECTION_ID BIGINT NOT NULL,
    PLAYLIST_ID BIGINT NOT NULL
);

ALTER TABLE COLLECTION_TRACKS ADD CONSTRAINT COLLECTION_TRACKS_COLLECTION_ID_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION(ID);
ALTER TABLE COLLECTION_TRACKS ADD CONSTRAINT COLLECTION_TRACKS_PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID);
