CREATE TABLE _ORDER (
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    TOTAL_ITEMS INT NOT NULL,
    TOTAL_PRICE DECIMAL(4,2) NOT NULL
);

ALTER TABLE _ORDER ADD PRIMARY KEY (ID);
ALTER TABLE _ORDER ADD CONSTRAINT ORDER_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);