CREATE TABLE EMAIL (
    ID BIGINT NOT NULL,
    OWNER VARCHAR(255) NOT NULL,
    EMAIL_FROM VARCHAR(255) NOT NULL,
    EMAIL_TO VARCHAR(255) NOT NULL,
    TEXT VARCHAR(255) NOT NULL,
    SEND_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    STATUS VARCHAR(255),
    SUBJECT VARCHAR(255),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE EMAIL_SEQ START WITH 1;

ALTER TABLE EMAIL ADD PRIMARY KEY (ID);
