CREATE TABLE PLAYLIST_TRACKS (
    PLAYLIST_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE PLAYLIST_TRACKS ADD CONSTRAINT PLAYLIST_TRACKS_PLAYLIST_ID_FK FOREIGN KEY (PLAYLIST_ID) REFERENCES PLAYLIST(ID);
ALTER TABLE PLAYLIST_TRACKS ADD CONSTRAINT PLAYLIST_TRACKS_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID);