CREATE TABLE ORDER_ITEMS (
	ORDER_ID BIGINT NOT NULL,
    TRACK_ID BIGINT NOT NULL
);

ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDER_ITEMS_ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES _ORDER(ID);
ALTER TABLE ORDER_ITEMS ADD CONSTRAINT ORDER_ITEMS_TRACK_ID_FK FOREIGN KEY (TRACK_ID) REFERENCES TRACK(ID);