CREATE TABLE _ORDER (
	ID BIGINT NOT NULL,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    TOTAL_ITEMS INT NOT NULL,
    TOTAL_PRICE DECIMAL(4,2) NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE ORDER_SEQ START WITH 1;

ALTER TABLE _ORDER ADD PRIMARY KEY (ID);
ALTER TABLE _ORDER ADD CONSTRAINT ORDER_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);