CREATE TABLE ALBUM (
	ID BIGINT NOT NULL UNIQUE,
    CUSTOMER_ID VARCHAR(20) NOT NULL UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    RECORD_ID BIGINT,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE ALBUM_SEQ START WITH 1;

ALTER TABLE ALBUM ADD PRIMARY KEY (ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_RECORD_ID_FK FOREIGN KEY (RECORD_ID) REFERENCES RECORD(ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);