CREATE TABLE RECORD_ALBUMS (
    RECORD BIGINT NOT NULL,
    ALBUM BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE RECORD_ALBUMS_SEQ START WITH 1;

ALTER TABLE RECORD_ALBUMS ADD PRIMARY KEY (RECORD, ALBUM);
ALTER TABLE RECORD_ALBUMS ADD CONSTRAINT RECORD_ALBUMS_RECORD_ID_FK FOREIGN KEY (RECORD) REFERENCES RECORD(ID);
ALTER TABLE RECORD_ALBUMS ADD CONSTRAINT RECORD_ALBUMS_ALBUM_ID_FK FOREIGN KEY (ALBUM) REFERENCES ALBUM(ID);