CREATE TABLE SUBSCRIPTION (
    ID BIGINT NOT NULL UNIQUE,
    _OPTION VARCHAR(255),
    PRICE NUMERIC(38,2),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE SUBSCRIPTION_SEQ START WITH 1;

ALTER TABLE SUBSCRIPTION ADD PRIMARY KEY (ID);

INSERT INTO SUBSCRIPTION(ID, _OPTION, PRICE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES
(1, 'STANDARD', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'STUDENT', 7.50, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'SOLO', 15.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'COUPLE', 25.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'FAMILY', 35.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);