CREATE TABLE REVIEW (
    ID BIGINT NOT NULL,
    SCORE FLOAT NOT NULL,
	TRACK BIGINT NOT NULL,
    CUSTOMER BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE REVIEW_SEQ START WITH 1;

ALTER TABLE REVIEW ADD PRIMARY KEY (ID);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID);
ALTER TABLE REVIEW ADD CONSTRAINT REVIEW_TRACK_ID_FK FOREIGN KEY (TRACK) REFERENCES TRACK(ID);
