CREATE TABLE SUBSCRIPTION (
    ID INT NOT NULL UNIQUE,
    _OPTION VARCHAR(20),
    PRICE DECIMAL(4,2),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE SUBSCRIPTION ADD PRIMARY KEY (ID);

INSERT INTO SUBSCRIPTION(ID, _OPTION, PRICE, CREATED_DATE, LAST_MODIFIED_DATE) VALUES
(1, 'STANDARD', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 'SOLO', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 'COUPLE', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 'STUDENT', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 'FAMILY', 0.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);