CREATE TABLE LEADS (
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    TEXT VARCHAR(200) NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE LEADS_SEQ START WITH 1;

ALTER TABLE LEADS ADD CONSTRAINT LEADS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);