CREATE TABLE PLAYLIST (
	ID BIGINT NOT NULL UNIQUE,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE PLAYLIST_SEQ START WITH 1;

ALTER TABLE PLAYLIST ADD PRIMARY KEY (ID);
ALTER TABLE PLAYLIST ADD CONSTRAINT PLAYLIST_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);