CREATE TABLE CART (
    ID BIGINT NOT NULL,
	CUSTOMER_ID VARCHAR(20) NOT NULL,
    TOTAL_PRICE DECIMAL(4,2) NOT NULL,
    TOTAL_ITEMS INT NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE CART_SEQ START WITH 1;

ALTER TABLE CART ADD PRIMARY KEY (ID);
ALTER TABLE CART ADD CONSTRAINT CART_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);