CREATE TABLE FOLLOW (
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    CUSTOMER_ID VARCHAR(20) NOT NULL,
    FOLLOWING_ID VARCHAR(20) NOT NULL,
    FOLLOW_DATE DATE NOT NULL
);

ALTER TABLE FOLLOW ADD PRIMARY KEY (ID);
ALTER TABLE FOLLOW ADD CONSTRAINT FOLLOW_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID);
ALTER TABLE FOLLOW ADD CONSTRAINT FOLLOW_FOLLOWING_ID_FK FOREIGN KEY (FOLLOWING_ID) REFERENCES CUSTOMER(CUSTOMER_ID);