CREATE TABLE SUBSCRIPTION (
    ID INT NOT NULL UNIQUE AUTO_INCREMENT,
    _OPTION VARCHAR(20)
);

ALTER TABLE SUBSCRIPTION ADD PRIMARY KEY (ID);

INSERT INTO SUBSCRIPTION(_OPTION) VALUES
("FREE"),
("MEDIUM"),
("ADVANCED");