CREATE TABLE ORDER_TABLE (
    ID BIGINT NOT NULL,
    CUSTOMER BIGINT NOT NULL,
    TOTAL_ITEMS INTEGER NOT NULL,
    TOTAL_PRICE NUMERIC(38, 2),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE ORDER_SEQ START WITH 1;

ALTER TABLE ORDER_TABLE ADD PRIMARY KEY (ID);
ALTER TABLE ORDER_TABLE ADD CONSTRAINT ORDER_TABLE_CUSTOMER_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID);