CREATE TABLE FOLLOW (
	ID BIGINT NOT NULL,
    CUSTOMER BIGINT NOT NULL,
    FOLLOWING BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE FOLLOW_SEQ START WITH 1;

ALTER TABLE FOLLOW ADD PRIMARY KEY (ID);
ALTER TABLE FOLLOW ADD CONSTRAINT FOLLOW_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID);
ALTER TABLE FOLLOW ADD CONSTRAINT FOLLOW_FOLLOWING_ID_FK FOREIGN KEY (FOLLOWING) REFERENCES CUSTOMER(ID);