CREATE TABLE TRACK (
	ID BIGINT NOT NULL UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    DURATION FLOAT NOT NULL,
    PRICE DECIMAL(4,2) NOT NULL,
    GENRE VARCHAR(20) NOT NULL,
    ALBUM_ID BIGINT NOT NULL,
    SPOTIFY_ID BIGINT,
    BEATPORT_ID BIGINT,
    ITUNES_ID BIGINT,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE TRACK_SEQ START WITH 1;

ALTER TABLE TRACK ADD PRIMARY KEY (ID);
ALTER TABLE TRACK ADD CONSTRAINT TRACK_ALBUM_ID_FK FOREIGN KEY (ALBUM_ID) REFERENCES ALBUM(ID);