CREATE TABLE MUSIC (
	ID LONG NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DURATION DOUBLE NOT  NULL,
    GENRE VARCHAR(255) NOT NULL
);

--CREATE TABLE MUSIC_SEQUENCE (
--    ID LONG NOT NULL AUTO_INCREMENT
--);