CREATE TABLE ALBUM (
	ID BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    RECORD_ID BIGINT,
    CUSTOMER_ID BIGINT
);

ALTER TABLE ALBUM ADD PRIMARY KEY (ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_RECORD_ID_FK FOREIGN KEY (RECORD_ID) REFERENCES RECORD(ID);
ALTER TABLE ALBUM ADD CONSTRAINT ALBUM_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID);