CREATE TABLE CART_TRACKS (
	CUSTOMER BIGINT NOT NULL,
    TRACK BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

ALTER TABLE CART_TRACKS ADD PRIMARY KEY (CUSTOMER, TRACK);
ALTER TABLE CART_TRACKS ADD CONSTRAINT CART_TRACKS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID);
ALTER TABLE CART_TRACKS ADD CONSTRAINT CART_TRACKS_TRACK_ID_FK FOREIGN KEY (TRACK) REFERENCES TRACK(ID);