CREATE TABLE RECORD (
	ID BIGINT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE RECORD_SEQ START WITH 1;

ALTER TABLE RECORD ADD PRIMARY KEY (ID);