CREATE TABLE CUSTOMER_ARTISTS (
    CUSTOMER BIGINT NOT NULL,
    ARTIST BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE CUSTOMER_ARTISTS_SEQ START WITH 1;

ALTER TABLE CUSTOMER_ARTISTS ADD PRIMARY KEY (CUSTOMER, ARTIST);
ALTER TABLE CUSTOMER_ARTISTS ADD CONSTRAINT CUSTOMER_ARTISTS_CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID);
ALTER TABLE CUSTOMER_ARTISTS ADD CONSTRAINT CUSTOMER_ARTISTS_ARTIST_ID_FK FOREIGN KEY (ARTIST) REFERENCES ARTIST(ID);