CREATE TABLE ALBUM_TRACKS (
    ID BIGINT NOT NULL UNIQUE,
    ALBUM BIGINT NOT NULL,
    TRACK BIGINT NOT NULL,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE ALBUM_TRACKS_SEQ START WITH 1;

ALTER TABLE ALBUM_TRACKS ADD PRIMARY KEY (ALBUM, TRACK);
ALTER TABLE ALBUM_TRACKS ADD CONSTRAINT ALBUM_TRACK_ID_FK FOREIGN KEY (ALBUM) REFERENCES ALBUM(ID);
ALTER TABLE ALBUM_TRACKS ADD CONSTRAINT TRACK_ALBUM_ID_FK FOREIGN KEY (TRACK) REFERENCES TRACK(ID);