CREATE TABLE TRACK (
    ID BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    GENRE VARCHAR(255) NOT NULL,
    IMAGE VARCHAR(255) NOT NULL,
    DURATION FLOAT4 NOT NULL,
    PATH VARCHAR(255) NOT NULL,
    PRICE INTEGER NOT NULL,
    ARTIST BIGINT NOT NULL,
    SPOTIFY_ID BIGINT,
    ITUNES_ID BIGINT,
    CREATED_DATE TIMESTAMP WITH TIME ZONE,
    LAST_MODIFIED_DATE TIMESTAMP WITH TIME ZONE
);

CREATE SEQUENCE TRACK_SEQ START WITH 1;

ALTER TABLE TRACK ADD PRIMARY KEY (ID);
ALTER TABLE TRACK ADD CONSTRAINT TRACK_ARTIST_ID_FK FOREIGN KEY (ARTIST) REFERENCES ARTIST(ID);