CREATE TABLE RECORD (
	ID BIGINT NOT NULL UNIQUE,
    NAME VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CREATED_DATE TIMESTAMP,
    LAST_MODIFIED_DATE TIMESTAMP
);

CREATE SEQUENCE RECORD_SEQ START WITH 1;

ALTER TABLE RECORD ADD PRIMARY KEY (ID);